const ProductContent = [
    {
        id: 1,
        name : "Eagle Industries MMAC",
        image : "https://ibb.co/GVg0Hjj",
        productType: "Vest/Plate Carrier",
        brand: "Eagle Industries",
        price: 2450000,
        size: "All size",
        colour: "Ranger Green",
        condition: "second used",
    },
    {
        id: 2,
        name : "Galaxy MP5K",
        image : "https://ibb.co/Xbvy5DG",
        productType: "Airsoft/AEG",
        brand: "Galaxy",
        price: 3000000,
        power: "Electric Power",
        material: "ABS, Polymer",
        condition: "second used",
    },
    {
        id: 3,
        name : "1.75 Bison Belt",
        image : "https://ibb.co/23jLqY5",
        productType: "belt",
        brand: "Ferro Concepts",
        price: 2450000,
        size: "M/L",
        colour: "Coyote Brown",
        condition: "second used",
    },
    {
        id: 4,
        name : "TM Hicapa 5.1",
        image : "https://ibb.co/tPw3VW9",
        productType: "airsoftGBB",
        brand: "Tokyo Marui",
        price: 3450000,
        Power: "Green Gas",
        material: "Metal Slide",
        condition: "BNIB",
    },
    {
        id: 5,
        name : "Comtac 3",
        image : "",
        productType: "Radio/Misc",
        brand: "3M Peltor",
        price: 5000000,
        size: "All size",
        colour: "Coyote Brown",
        condition: "BNIB",
    },
    {
        id: 6,
        name : "HK 416 AEG",
        image : "",
        productType: "Airsoft/AEG",
        brand: "Vega Force Company",
        price: 7450000,
        power: "Electric Power",
        material: "Full Metal, Annodized 7075",
        condition: "second used",
    }
]
  

export default ProductContent